name: Pipeline
on:
  push:

env:
  TARGET: crayon
  IS_LIB: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux-x64
          - os: windows-latest
            platform: windows-x64
          - os: macos-latest
            platform: macos-x64

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3
          
      - name: Configure rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Enable Cargo caching
        uses: Swatinem/rust-cache@v2

      - name: Test
        run: cargo test --verbose

      - name: Build
        run: cargo build --release --verbose

      - name: Compress Windows executable
        if: env.IS_LIB == false && runner.os == 'Windows'
        run: zip ${{ env.TARGET }}-${{ matrix.platform}}-${{ github.ref_name }}.zip ./target/release/${{ env.TARGET }}.exe

      - name: Compress Unix executable
        if: env.IS_LIB == false && runner.os != 'Windows'
        run: zip ${{ env.TARGET }}-${{ matrix.platform}}-${{ github.ref_name }}.zip ./target/release/${{ env.TARGET }}

      - name: Upload ${{ matrix.platform }} artifact
        if: env.IS_LIB == false
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.TARGET }}-${{ matrix.platform }}-${{ github.ref_name }}
          path: ./${{ env.TARGET }}-${{ matrix.platform }}-${{ github.ref_name }}.zip